version: "3"
services:
  wp-db:
    image: "postgres"
    container_name: "balloon-shop"
    environment:
      - POSTGRES_USER=wp
      - POSTGRES_PASSWORD=wp123
      - POSTGRES_DB=balloon-shop
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data